### ISSUE TITLE
zowe editor plugin fails to build because of node-sass failure

### ISSUE THREAD

**Issue by philippe-richard** [ibmruntimes/node#112]
npm i for zowe-editor (among others) fails because there's a dependency on sass which needs a compiler, and assumes some  options which appear to not be parsed correctly for Z's nodejs; see the log below:

PRICHAR@X9:/X9/var/zowe/0.9.0/zlux-editor/webClient #npm i
?øÁ>ËËÄ?>ÃÑÅÃ/ÑÁÀÁÊÊ?ÊË`ËÈÁ_%ÑÂÊ/Ê`Ã?øÁ>áàäñ+?ËÍÄÇÃÑ%Á?ÊÀÑÊÁÄÈ?Ê`[..............          
> node-sass@4.10.0 install /X9/var/zowe/0.9.0/zlux-editor/webClient/node_modules          /node-sass
> node scripts/install.js

?øÁ>ËËÄ?>ÃÑÅÃ/ÑÁÀÁÊÊ?ÊË`ËÈÁ_%ÑÂÊ/Ê`Ã?øÁ>áàäñ+?ËÍÄÇÃÑ%Á?ÊÀÑÊÁÄÈ?Ê`Downloading bin          ary from https://github.com/sass/node-sass/releases/download/v4.10.0/os390-s390x          -48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/os3          90-s390x-48_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.10.0 postinstall /X9/var/zowe/0.9.0/zlux-editor/webClient/node_mod          ules/node-sass
> node scripts/build.js

Building: /Z23R01/usr/lpp/IBM/nodejs/node-v6.14.4-os390-s390x/bin/node /X9/var/z          owe/0.9.0/zlux-editor/webClient/node_modules/node-gyp/bin/node-gyp.js rebuild --          verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/Z23R01/usr/lpp/IBM/nodejs/node-v6.14.4-os390-s390x/bin/node',
gyp verb cli   '/X9/var/zowe/0.9.0/zlux-editor/webClient/node_modules/node-gyp/b          in/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@6.14.4 | os390 | s390x
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/rocket/python-2.7.13-anaconda-2017          -04-12/python27/bin/python2
gyp verb check python version `/usr/local/rocket/python-2.7.13-anaconda-2017-04-          12/python27/bin/python2 -c "import sys; print "2.7.13
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node v          ersion: 6.14.4
gyp verb command install [ '6.14.4' ]
?øÁ>ËËÄ?>ÃÑÅÃ/ÑÁÀÁÊÊ?ÊË`ËÈÁ_%ÑÂÊ/Ê`Ã?øÁ>áàäñ+?ËÍÄÇÃÑ%Á?ÊÀÑÊÁÄÈ?Ê`gyp verb instal          l input version string "6.14.4"
gyp verb install installing version: 6.14.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 6.14.4
gyp verb build dir attempting to create "build" dir: /X9/var/zowe/0.9.0/zlux-edi          tor/webClient/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /X9/var/zowe/0.9.0/zlux-edi          tor/webClient/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /X9/var/zowe/0.9.0/zlux-edit          or/webClient/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /X9/var/zowe/0.9.0/zlux-editor/webC          lient/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /X9/var/zowe/0.9.0/zlux-editor/webC          lient/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp verb node-gyp root npm_parent_directory is zlux-editor
gyp verb node-gyp root Finding node root directory
gyp verb find exports file Found exports file: /Z23R01/usr/lpp/IBM/nodejs/node-v          6.14.4-os390-s390x/lib/libnode.x
gyp info spawn /usr/local/rocket/python-2.7.13-anaconda-2017-04-12/python27/bin/          python2
gyp info spawn args [ '/X9/var/zowe/0.9.0/zlux-editor/webClient/node_modules/nod          e-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/X9/var/zowe/0.9.0/zlux-editor/webClient/node_modules/nod          e-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/X9/var/zowe/0.9.0/zlux-editor/webClient/node_modules/nod          e-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/u/prichar/.node-gyp/6.14.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/u/prichar/.node-gyp/6.14.4',
gyp info spawn args   '-Dnode_exp_file=/Z23R01/usr/lpp/IBM/nodejs/node-v6.14.4-o          s390-s390x/lib/libnode.x',
gyp info spawn args   '-Dnode_gyp_dir=/X9/var/zowe/0.9.0/zlux-editor/webClient/n          ode_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/u/prichar/.node-gyp/6.14.4/<(target_arch          )/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/X9/var/zowe/0.9.0/zlux-editor/webClien          t/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture s390x
gyp verb node dev dir /u/prichar/.node-gyp/6.14.4
gyp verb `which` succeeded for `make` /usr/local/rocket/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/X9/var/zowe/0.9.0/zlux-editor/webClient/node_modules/          node-sass/build'
  eb2as.sh '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SH          ARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS          =64' '-DLIBSASS_VERSION="3.5.4"' -I/u/prichar/.node-gyp/6.14.4/include/node -I/u          /prichar/.node-gyp/6.14.4/src -I/u/prichar/.node-gyp/6.14.4/deps/openssl/config           -I/u/prichar/.node-gyp/6.14.4/deps/openssl/openssl/include -I/u/prichar/.node-gy          p/6.14.4/deps/uv/include -I/u/prichar/.node-gyp/6.14.4/deps/zlib -I/u/prichar/.n          ode-gyp/6.14.4/deps/v8/include -I../src/libsass/include  -q64 -Wc,DLL -qlonglong           -O3 -fno-omit-frame-pointer ### **-std=c++0x** -fexceptions -frtti -qmakedep=gcc -MF ./          Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Rel          ease/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
### **FSUM3210 njsc++: Command option -td=c++0x contains an incorrect subargument.
FSUM3210 njsc++: Command option -td=c++0x contains an incorrect subargument.**
src/libsass.target.mk:141: recipe for target 'Release/obj.target/libsass/src/lib          sass/src/ast.o' failed
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 40
make: Leaving directory '/X9/var/zowe/0.9.0/zlux-editor/webClient/node_modules/n          ode-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/X9/var/zowe/0.9.0/zlux-editor/webCli          ent/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces          s.js:219:12)
gyp ERR! System OS/390 26.00
gyp ERR! command "/Z23R01/usr/lpp/IBM/nodejs/node-v6.14.4-os390-s390x/bin/node"           "/X9/var/zowe/0.9.0/zlux-editor/webClient/node_modules/node-gyp/bin/node-gyp.js"           "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="           "--libsass_library="
gyp ERR! cwd /X9/var/zowe/0.9.0/zlux-editor/webClient/node_modules/node-sass
gyp ERR! node -v v6.14.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN @ngtools/webpack@1.10.2 requires a peer of webpack@^2.2.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN html-webpack-plugin@2.30.1 requires a peer of webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@1.12.2 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@2.11.2 requires a peer of webpack@^2.2.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-subresource-integrity@1.0.4 requires a peer of webpack@^1.12.11 || ~2 || ~3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"os390","arch":"s390x"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.10.0 (node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.10.0 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 130 packages in 41.045s
PRICHAR@X9:/X9/var/zowe/0.9.0/zlux-editor/webClient

**Comment by joransiu** [comment]
Hi @philippe-richard : Thanks for reporting this issue.  It looks like njsc++ currently doesn't support `-std=c++0x` option.  This was specified in https://github.com/sass/node-sass/blob/master/binding.gyp#L85.   I'm checking with our C/C++ colleagues about this support.  We may have to add a zOS rule in there to not specify the option, and see if that allows libsass to compile and function properly on z/OS.

**Comment by 1000TurquoisePogs** [comment]
This seems to still be true with the 8.15.1 beta:
```
FSUM3257 njsc++: Option -std=c++0x is not recognized. Option will be ignored.
FSUM3277 njsc++: The specified option "-qdll" is not supported.
FSUM3277 njsc++: The specified option "-qtarget=zosv2r1" is not supported.
FSUM3277 njsc++: The specified option "-qdll" is not supported.
FSUM3277 njsc++: The specified option "-qtarget=zosv2r1" is not supported.
```
