### ISSUE TITLE
ZOWESVR error : Eureka request :  connection refused.

### ISSUE THREAD

**Issue by yugeshpothuru** [ibmruntimes/node#127]
Problem making eureka request { Error: connect ECONNREFUSED 10.242.55.48:10011 
    at Object.exports._errnoException (util.js:1020:11)                        
    at exports._exceptionWithHostPort (util.js:1043:20)                        
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)            
  code: 'ECONNREFUSED',                                                        
  errno: 'ECONNREFUSED',                                                       
  syscall: 'connect',                                                          
  address: '10.242.55.48',                                                     
  port: 10011 }                                                                

Receiving this error. I have tried the below steps.

Added 127.0.0.1 as NSINTERADDR and refreshed resolver didnt work
added 10.242.55.48 as NSINTERADDR and refreshed resolver didnt work
added 10011 to the port list and issue VARY TCIP, obeyfile didnt work.

can someone help me with any more checks that I can do.

**Comment by yugeshpothuru** [comment]
i'm running zowe in a zpdt system.

**Comment by 1000TurquoisePogs** [comment]
I think you can close this, it's a zowe issue instead of a nodejs issue.
The reason it occurs is app-server continually tries to connect to apiml, but starts up quicker than apiml, so there will be a few failed attempts before eventual success with the eureka request.
