### ISSUE TITLE
Building Nodejs for ppc e500

### ISSUE THREAD

**Issue by arrathin** [ibmruntimes/node#149]
I am trying to build node js for ppc 32. Though there is no official support, am giving a try since it is required for one of my platform. Can you please tell me if there is any known guide lines to build node js for ppc 32. 

I did a hack and succeeded with build. However, the execution crashes with "ILLEGAL instruction" error.

Program received signal SIGILL, Illegal instruction.
[Switching to Thread 805427584 (LWP 6480)]
0x2f70ffa4 in ?? ()
(gdb) bt
#0 0x2f70ffa4 in ?? ()

#1 0x335bbc48 in ?? ()

warning: Previous frame inner to this frame (corrupt stack?)

(gdb)

GitHub Node Version: node-v8.11.3

# cat /proc/cpuinfo

processor : 0

cpu : e500

revision : 2.0 (pvr 8020 0020)

bogomips : 524.28

chipset : 8555E

Vendor : Motorola SPS

# LD_SHOW_AUXV=1 /bin/true

AT_DCACHEBSIZE: 0x20 - 32 bit

AT_ICACHEBSIZE: 0x20 - 32 Bit

AT_UCACHEBSIZE: 0x0

AT_HWCAP: 84c00000

AT_PAGESZ: 4096

AT_CLKTCK: 100

AT_PHDR: 0x10000034

AT_PHENT: 32 @tellison @andrewlow @mtbrandy

**Comment by arrathin** [comment]
Need your quick support for this issue.

**Comment by arrathin** [comment]
@Wayne Zhang
 @IBM @ibmruntimes

**Comment by arrathin** [comment]
@joransiu

**Comment by arrathin** [comment]
Guys, Could you please suggest your tough on this issue.

**Comment by richardlau** [comment]
I’d suggest looking at https://github.com/nodejs/node/issues/30323 for what others have tried so far.
