### ISSUE TITLE
Starting  Node.js process manager pm2 causes an ABEND.

### ISSUE THREAD

**Issue by vganich** [ibmruntimes/node#161]
We found the issue with IBM SDK for Node.js for z/OS after upgrade to V12. 

Specifically, the user had  been encountering problem starting  Node.js process manager pm2.

**Comment by sam-github** [comment]
Upgrade from what to v12?

What issues? Logs would be useful here.

How to reproduce?

**Comment by IgorTodorovskiIBM** [comment]
This is a z/OS specific issue. 

pm2 no longer works with Node v12 - z/OS

The symptom is a hang, reproducible by running these steps:

mkdir defectproj && cd defectproj
npm init --yes
npm install pm2
./node_modules/pm2/bin/pm2 --help
Result is:

...
[PM2] Spawning PM2 daemon with pm2_home=/home/itodoro/.pm2
(hangs)
...
Further inspection reveals that pm2 stores a log file in $HOME/.pm2/pm2.log, which contains the following error:

2020-02-27T12:08:13: PM2 log: ===============================================================================
2020-02-27T12:08:13: PM2 log: --- PM2 global error caught ---------------------------------------------------
2020-02-27T12:08:13: PM2 log: Time                 : Thu Feb 27 2020 12:08:13 GMT-0500 (Eastern Standard Time)
2020-02-27T12:08:13: PM2 error: write EPIPE
2020-02-27T12:08:13: PM2 error: Error: write EPIPE
    at process.target._send (internal/child_process.js:827:20)
    at process.target.send (internal/child_process.js:697:19)
    at module.exports.Daemon.sendReady (/home/itodoro/install_test/node-v12.15.0-os390-s390x/package/node_modules/pm2/lib/Daemon.js:316:13)
    at RepSocket.<anonymous> (/home/itodoro/install_test/node-v12.15.0-os390-s390x/package/node_modules/pm2/lib/Daemon.js:152:10)
    at Object.onceWrapper (events.js:299:28)
    at RepSocket.emit (events.js:210:5)
    at RepSocket.EventEmitter.emit (domain.js:475:20)
    at Server.emit (events.js:210:5)
    at Server.EventEmitter.emit (domain.js:498:23)
    at emitListeningNT (net.js:1341:10)
2020-02-27T12:08:13: PM2 log: ===============================================================================
2020-02-27T12:08:13: PM2 error: [PM2] Resurrecting PM2

**Comment by IgorTodorovskiIBM** [comment]
We have a fix that we will be releasing in our next PTF

**Comment by IgorTodorovskiIBM** [comment]
Fix is available in the April 2020 PTF: https://www.ibm.com/support/pages/fix-list-ibm-sdk-nodejs-zos#030420
