### ISSUE TITLE
AIX test-net-settimeout intermittent failure

### ISSUE THREAD

**Issue by tunniclm** [ibmruntimes/node#26]
Failure stack:

```
assert.js:98
  throw new assert.AssertionError({
        ^
AssertionError: false == true
    at null._onTimeout (/home/tunniclm/Projects/node.aix/test/simple/test-net-settimeout.js:54:12)
    at Timer.listOnTimeout (timers.js:132:15)
```

**Comment by jBarz** [comment]
This test passes on the latest node with rc=0.
> out/Release/node test/parallel/test-net-settimeout.js

I tested this on aix 6.1
