### ISSUE TITLE
npm install -g sqlite3 fails on z/OS

### ISSUE THREAD

**Issue by smartmouse** [ibmruntimes/node#72]
> sqlite3@3.1.8 install /u/slbld/node/lib/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v14-os390-s390x.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and node@0.12.17 (node-v14 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/u/slbld/node/lib/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
Traceback (most recent call last):
  File "./extract.py", line 7, in <module>
    tfile = tarfile.open(tarball,'r:gz');
  File "/u/slbld/python-2.7.6/lib/python2.7/tarfile.py", line 1678, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/u/slbld/python-2.7.6/lib/python2.7/tarfile.py", line 1719, in gzopen
    raise CompressionError("gzip module is not available")
tarfile.CompressionError: gzip module is not available
deps/action_before_build.target.mk:13: recipe for target 'Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c' failed
make: *** [Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c] Error 1
make: Leaving directory '/u/slbld/node/lib/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/u/slbld/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1078:12)
gyp ERR! System Öâaóùð òôKðð
gyp ERR! command "/u/slbld/node/bin/node" "/u/slbld/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/u/slbld/node/lib/node_modules/sqlite3/lib/binding/node-v14-os390-s390x/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/u/slbld/node/lib/node_modules/sqlite3/lib/binding/node-v14-os390-s390x"
gyp ERR! cwd /u/slbld/node/lib/node_modules/sqlite3
gyp ERR! node -v v0.12.17
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/u/slbld/node/bin/node /u/slbld/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/u/slbld/node/lib/node_modules/sqlite3/lib/binding/node-v14-os390-s390x/node_sqlite3.node --module_name=node_sqlite3 --module_path=/u/slbld/node/lib/node_modules/sqlite3/lib/binding/node-v14-os390-s390x' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/u/slbld/node/lib/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1019:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1091:5)
node-pre-gyp ERR! System Öâaóùð òôKðð
node-pre-gyp ERR! command "node" "/u/slbld/node/lib/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /u/slbld/node/lib/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.17
node-pre-gyp ERR! node -v v0.6.31
node-pre-gyp ERR! not ok 
Failed to execute '/u/slbld/node/bin/node /u/slbld/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/u/slbld/node/lib/node_modules/sqlite3/lib/binding/node-v14-os390-s390x/node_sqlite3.node --module_name=node_sqlite3 --module_path=/u/slbld/node/lib/node_modules/sqlite3/lib/binding/node-v14-os390-s390x' (1)
npm ERR! Öâaóùð òôKðð
npm ERR! argv "/u/slbld/node/bin/node" "/u/slbld/node/bin/npm" "install" "-g" "sqlite3"
npm ERR! node v0.12.17
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.8 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /u/slbld/npm-debug.log
-

**Comment by jBarz** [comment]
The tar functionality in python on zOS is not functional.
I have made the changes in node-sqlite to work on zOS.
I am awaiting approval to upstream these changes.
In the meantime, you can npm install from my github repo.

npm -g install https://github.com/jBarz/node-sqlite3/tarball/v3.1.4.zos --link https://github.com/jBarz/nan/tarball/master

**Comment by jBarz** [comment]
Here is the pull request. 
https://github.com/mapbox/node-sqlite3/pull/753
