### ISSUE TITLE
npm install -g loopback-connector-soap on z/os has issues

### ISSUE THREAD

**Issue by smartmouse** [ibmruntimes/node#73]
:/u/slbld>npm install -g loopback-connector-soap   
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.12.17","npm":"2.15.1"})
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN engine xmlbuilder@8.2.2: wanted: {"node":">=4.0"} (current: {"node":"0.12.17","npm":"2.15.1"})
 
> ursa@0.9.4 install /u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa
> node-gyp rebuild

make: Entering directory '/u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
CCN0465(W) "MAKEDEP" requires at most "0" sub-option(s) to be specified. "1" were given.
"../node_modules/nan/nan_implementation_12_inl.h", line 127.61: CCN5216 (W) An expression of type "void (*)(const FunctionCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan_implementation_12_inl.h", line 99.59: CCN5216 (W) An expression of type "void (*)(const FunctionCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 1926.50: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 1931.52: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, Local<v8::Value>, const PropertyCallbackInfo<void> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 1969.50: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 1978.52: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, Local<v8::Value>, const PropertyCallbackInfo<void> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2027.50: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2032.52: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, Local<v8::Value>, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2038.52: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Integer> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2044.52: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Boolean> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2050.52: CCN5216 (W) An expression of type "void (*)(const PropertyCallbackInfo<v8::Array> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2097.50: CCN5216 (W) An expression of type "void (*)(unsigned int, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2102.52: CCN5216 (W) An expression of type "void (*)(unsigned int, Local<v8::Value>, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2108.52: CCN5216 (W) An expression of type "void (*)(unsigned int, const PropertyCallbackInfo<v8::Integer> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2114.52: CCN5216 (W) An expression of type "void (*)(unsigned int, const PropertyCallbackInfo<v8::Boolean> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2120.52: CCN5216 (W) An expression of type "void (*)(const PropertyCallbackInfo<v8::Array> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2153.50: CCN5216 (W) An expression of type "void (*)(const FunctionCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2175.50: CCN5216 (W) An expression of type "void (*)(const FunctionCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"/u/slbld/.node-gyp/0.12.17/include/node/uv.h", line 1488.16: CCN6410 (W) The function "uv_tty_set_mode" specified in "pragma export" is not uniquely identified. The pragma is ignored.
  SOLINK_MODULE(target) Release/obj.target/ursaNative.node
 IEW2456E 9207 SYMBOL __dl__Q2_3NanEI20EscapableHandleScopeFPvUl UNRESOLVED.    
          MEMBER COULD NOT BE INCLUDED FROM THE DESIGNATED CALL LIBRARY.        
 IEW2456E 9207 SYMBOL __dl__Q2_3NanEI11HandleScopeFPvUl UNRESOLVED.  MEMBER     
          COULD NOT BE INCLUDED FROM THE DESIGNATED CALL LIBRARY.               
FSUM3065 The LINKEDIT step ended with return code 8.
ursaNative.target.mk:123: recipe for target 'Release/obj.target/ursaNative.node' failed
make: *** [Release/obj.target/ursaNative.node] Error 3
make: Leaving directory '/u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/u/slbld/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1078:12)
gyp ERR! System Öâaóùð òôKðð
gyp ERR! command "node" "/u/slbld/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa
gyp ERR! node -v v0.12.17
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing ursa@0.9.4
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apiconnect-cli-util requires async@'1.5.1' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/async,
npm WARN unmet dependency which is version 1.5.2
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apiconnect-cli-util requires bluebird@'^1.x' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/bluebird,
npm WARN unmet dependency which is version 3.4.6
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apiconnect-cli-util requires lodash@'4.0.x' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/lodash,
npm WARN unmet dependency which is version 4.16.5
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/generator-loopback requires request@'^2.60.0' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/request,
npm WARN unmet dependency which is version 2.55.0
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/pug-lexer requires is-expression@'^3.0.0' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/is-expression,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apiconnect-assembly requires angular-marked@'0.x' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/angular-marked,
npm WARN unmet dependency which is version 1.2.2
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apiconnect-assembly requires angular-native-dragdrop@'1.1.2' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/angular-native-dragdrop,
npm WARN unmet dependency which is version 1.2.2
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apiconnect-assembly requires angular-ui-validate@'1.2.1' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/angular-ui-validate,
npm WARN unmet dependency which is version 1.2.2
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apiconnect-assembly requires glob@'^7.0.3' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/glob,
npm WARN unmet dependency which is version 6.0.4
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apiconnect-assembly requires tv4@'^1.2.7' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/tv4,
npm WARN unmet dependency which is version 1.1.12
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apiconnect-cli-login-bluemix requires apiconnect-cli-config@'^2.x' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apiconnect-cli-config,
npm WARN unmet dependency which is version 3.0.1
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apiconnect-collective-jmx requires async@'^2.0.1' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/async,
npm WARN unmet dependency which is version 1.5.2
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apiconnect-collective-jmx requires lodash@'^3.10.1' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/lodash,
npm WARN unmet dependency which is version 4.16.5
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apiconnect-collective-jmx requires request@'^2.65.0' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/request,
npm WARN unmet dependency which is version 2.55.0
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/loopback requires async@'^2.0.1' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/async,
npm WARN unmet dependency which is version 1.5.2
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/loopback requires underscore.string@'^3.0.3' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/underscore.string,
npm WARN unmet dependency which is version 2.3.3
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/loopback-datasource-juggler requires async@'~1.0.0' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/async,
npm WARN unmet dependency which is version 1.5.2
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/loopback-datasource-juggler requires qs@'^3.1.0' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/qs,
npm WARN unmet dependency which is version 6.3.0
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/microgateway requires apiconnect-cli-config@'^2.x' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apiconnect-cli-config,
npm WARN unmet dependency which is version 3.0.1
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/microgateway requires express-session@'^1.13.0' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/express-session,
npm WARN unmet dependency which is version 1.11.3
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/microgateway requires fs-extra@'^0.30.0' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/fs-extra,
npm WARN unmet dependency which is version 0.26.7
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/microgateway requires glob@'^7.0.3' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/glob,
npm WARN unmet dependency which is version 6.0.4
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/microgateway requires js-yaml@'^3.5.2' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/js-yaml,
npm WARN unmet dependency which is version 3.4.6
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/microgateway requires request@'^2.69.0' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/request,
npm WARN unmet dependency which is version 2.55.0
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/microgateway requires semver@'^4.1.0' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/semver,
npm WARN unmet dependency which is version 5.3.0
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/swagger-ui requires swagger-client@'2.0.36' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/swagger-client,
npm WARN unmet dependency which is version 2.1.23
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/swagger-ui requires handlebars@'~1.0.10' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/handlebars,
npm WARN unmet dependency which is version 4.0.5
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/swagger-ui requires less@'~1.4.2' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/less,
npm WARN unmet dependency which is version 2.7.1
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apiconnect-collective-controller-api requires request@'^2.69.0' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/request,
npm WARN unmet dependency which is version 2.55.0
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apim-ui requires glob@'^7.0.3' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/glob,
npm WARN unmet dependency which is version 6.0.4
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apim-ui requires js-yaml@'^3.6.0' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/js-yaml,
npm WARN unmet dependency which is version 3.4.6
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apim-ui requires request@'^2.69.0' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/request,
npm WARN unmet dependency which is version 2.55.0
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/apim-ui requires tv4@'^1.2.7' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/tv4,
npm WARN unmet dependency which is version 1.1.12
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/json-schema-generator/node_modules/request/node_modules/hawk requires hoek@'0.9.x' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/hoek,
npm WARN unmet dependency which is version 2.16.3
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/json-schema-generator/node_modules/request/node_modules/hawk requires boom@'0.4.x' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/boom,
npm WARN unmet dependency which is version 2.10.1
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/json-schema-generator/node_modules/request/node_modules/hawk requires cryptiles@'0.2.x' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/cryptiles,
npm WARN unmet dependency which is version 2.0.5
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/json-schema-generator/node_modules/request/node_modules/hawk requires sntp@'0.2.x' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/sntp,
npm WARN unmet dependency which is version 1.0.9
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/json-schema-generator/node_modules/request/node_modules/bl/node_modules/readable-stream requires isarray@'0.0.1' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/isarray,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/json-schema-generator/node_modules/request/node_modules/form-data/node_modules/mime-types requires mime-db@'~1.5.0' but will load
npm WARN unmet dependency /u/slbld/node/lib/node_modules/apiconnect/node_modules/mime-db,
npm WARN unmet dependency which is version 1.24.0
loopback-connector-soap@3.0.1 /u/slbld/node/lib/node_modules/loopback-connector-soap
├── debug@2.3.3 (ms@0.7.2)
├── request@2.79.0 (is-typedarray@1.0.0, oauth-sign@0.8.2, aws-sign2@0.6.0, forever-agen

**Comment by smartmouse** [comment]
we can close this one which duplicated
